// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: consulteroffre.proto

package org.isd.stubs;

public final class Consulteroffre {
  private Consulteroffre() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ConsultRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ConsultRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string dateDebut = 1;</code>
     * @return The dateDebut.
     */
    java.lang.String getDateDebut();
    /**
     * <code>string dateDebut = 1;</code>
     * @return The bytes for dateDebut.
     */
    com.google.protobuf.ByteString
        getDateDebutBytes();

    /**
     * <code>string dateFin = 2;</code>
     * @return The dateFin.
     */
    java.lang.String getDateFin();
    /**
     * <code>string dateFin = 2;</code>
     * @return The bytes for dateFin.
     */
    com.google.protobuf.ByteString
        getDateFinBytes();

    /**
     * <code>int32 nbPersonne = 3;</code>
     * @return The nbPersonne.
     */
    int getNbPersonne();
  }
  /**
   * Protobuf type {@code ConsultRequest}
   */
  public  static final class ConsultRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ConsultRequest)
      ConsultRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ConsultRequest.newBuilder() to construct.
    private ConsultRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ConsultRequest() {
      dateDebut_ = "";
      dateFin_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ConsultRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ConsultRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              dateDebut_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              dateFin_ = s;
              break;
            }
            case 24: {

              nbPersonne_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.isd.stubs.Consulteroffre.internal_static_ConsultRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.isd.stubs.Consulteroffre.internal_static_ConsultRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.isd.stubs.Consulteroffre.ConsultRequest.class, org.isd.stubs.Consulteroffre.ConsultRequest.Builder.class);
    }

    public static final int DATEDEBUT_FIELD_NUMBER = 1;
    private volatile java.lang.Object dateDebut_;
    /**
     * <code>string dateDebut = 1;</code>
     * @return The dateDebut.
     */
    public java.lang.String getDateDebut() {
      java.lang.Object ref = dateDebut_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dateDebut_ = s;
        return s;
      }
    }
    /**
     * <code>string dateDebut = 1;</code>
     * @return The bytes for dateDebut.
     */
    public com.google.protobuf.ByteString
        getDateDebutBytes() {
      java.lang.Object ref = dateDebut_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dateDebut_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATEFIN_FIELD_NUMBER = 2;
    private volatile java.lang.Object dateFin_;
    /**
     * <code>string dateFin = 2;</code>
     * @return The dateFin.
     */
    public java.lang.String getDateFin() {
      java.lang.Object ref = dateFin_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dateFin_ = s;
        return s;
      }
    }
    /**
     * <code>string dateFin = 2;</code>
     * @return The bytes for dateFin.
     */
    public com.google.protobuf.ByteString
        getDateFinBytes() {
      java.lang.Object ref = dateFin_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dateFin_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NBPERSONNE_FIELD_NUMBER = 3;
    private int nbPersonne_;
    /**
     * <code>int32 nbPersonne = 3;</code>
     * @return The nbPersonne.
     */
    public int getNbPersonne() {
      return nbPersonne_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getDateDebutBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, dateDebut_);
      }
      if (!getDateFinBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, dateFin_);
      }
      if (nbPersonne_ != 0) {
        output.writeInt32(3, nbPersonne_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDateDebutBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, dateDebut_);
      }
      if (!getDateFinBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, dateFin_);
      }
      if (nbPersonne_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, nbPersonne_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.isd.stubs.Consulteroffre.ConsultRequest)) {
        return super.equals(obj);
      }
      org.isd.stubs.Consulteroffre.ConsultRequest other = (org.isd.stubs.Consulteroffre.ConsultRequest) obj;

      if (!getDateDebut()
          .equals(other.getDateDebut())) return false;
      if (!getDateFin()
          .equals(other.getDateFin())) return false;
      if (getNbPersonne()
          != other.getNbPersonne()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DATEDEBUT_FIELD_NUMBER;
      hash = (53 * hash) + getDateDebut().hashCode();
      hash = (37 * hash) + DATEFIN_FIELD_NUMBER;
      hash = (53 * hash) + getDateFin().hashCode();
      hash = (37 * hash) + NBPERSONNE_FIELD_NUMBER;
      hash = (53 * hash) + getNbPersonne();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.isd.stubs.Consulteroffre.ConsultRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.isd.stubs.Consulteroffre.ConsultRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.isd.stubs.Consulteroffre.ConsultRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.isd.stubs.Consulteroffre.ConsultRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.isd.stubs.Consulteroffre.ConsultRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.isd.stubs.Consulteroffre.ConsultRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.isd.stubs.Consulteroffre.ConsultRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.isd.stubs.Consulteroffre.ConsultRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.isd.stubs.Consulteroffre.ConsultRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.isd.stubs.Consulteroffre.ConsultRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.isd.stubs.Consulteroffre.ConsultRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.isd.stubs.Consulteroffre.ConsultRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.isd.stubs.Consulteroffre.ConsultRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ConsultRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ConsultRequest)
        org.isd.stubs.Consulteroffre.ConsultRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.isd.stubs.Consulteroffre.internal_static_ConsultRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.isd.stubs.Consulteroffre.internal_static_ConsultRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.isd.stubs.Consulteroffre.ConsultRequest.class, org.isd.stubs.Consulteroffre.ConsultRequest.Builder.class);
      }

      // Construct using org.isd.stubs.Consulteroffre.ConsultRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        dateDebut_ = "";

        dateFin_ = "";

        nbPersonne_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.isd.stubs.Consulteroffre.internal_static_ConsultRequest_descriptor;
      }

      @java.lang.Override
      public org.isd.stubs.Consulteroffre.ConsultRequest getDefaultInstanceForType() {
        return org.isd.stubs.Consulteroffre.ConsultRequest.getDefaultInstance();
      }

      @java.lang.Override
      public org.isd.stubs.Consulteroffre.ConsultRequest build() {
        org.isd.stubs.Consulteroffre.ConsultRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.isd.stubs.Consulteroffre.ConsultRequest buildPartial() {
        org.isd.stubs.Consulteroffre.ConsultRequest result = new org.isd.stubs.Consulteroffre.ConsultRequest(this);
        result.dateDebut_ = dateDebut_;
        result.dateFin_ = dateFin_;
        result.nbPersonne_ = nbPersonne_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.isd.stubs.Consulteroffre.ConsultRequest) {
          return mergeFrom((org.isd.stubs.Consulteroffre.ConsultRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.isd.stubs.Consulteroffre.ConsultRequest other) {
        if (other == org.isd.stubs.Consulteroffre.ConsultRequest.getDefaultInstance()) return this;
        if (!other.getDateDebut().isEmpty()) {
          dateDebut_ = other.dateDebut_;
          onChanged();
        }
        if (!other.getDateFin().isEmpty()) {
          dateFin_ = other.dateFin_;
          onChanged();
        }
        if (other.getNbPersonne() != 0) {
          setNbPersonne(other.getNbPersonne());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.isd.stubs.Consulteroffre.ConsultRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.isd.stubs.Consulteroffre.ConsultRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object dateDebut_ = "";
      /**
       * <code>string dateDebut = 1;</code>
       * @return The dateDebut.
       */
      public java.lang.String getDateDebut() {
        java.lang.Object ref = dateDebut_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          dateDebut_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string dateDebut = 1;</code>
       * @return The bytes for dateDebut.
       */
      public com.google.protobuf.ByteString
          getDateDebutBytes() {
        java.lang.Object ref = dateDebut_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dateDebut_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string dateDebut = 1;</code>
       * @param value The dateDebut to set.
       * @return This builder for chaining.
       */
      public Builder setDateDebut(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        dateDebut_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string dateDebut = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDateDebut() {
        
        dateDebut_ = getDefaultInstance().getDateDebut();
        onChanged();
        return this;
      }
      /**
       * <code>string dateDebut = 1;</code>
       * @param value The bytes for dateDebut to set.
       * @return This builder for chaining.
       */
      public Builder setDateDebutBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        dateDebut_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object dateFin_ = "";
      /**
       * <code>string dateFin = 2;</code>
       * @return The dateFin.
       */
      public java.lang.String getDateFin() {
        java.lang.Object ref = dateFin_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          dateFin_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string dateFin = 2;</code>
       * @return The bytes for dateFin.
       */
      public com.google.protobuf.ByteString
          getDateFinBytes() {
        java.lang.Object ref = dateFin_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dateFin_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string dateFin = 2;</code>
       * @param value The dateFin to set.
       * @return This builder for chaining.
       */
      public Builder setDateFin(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        dateFin_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string dateFin = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDateFin() {
        
        dateFin_ = getDefaultInstance().getDateFin();
        onChanged();
        return this;
      }
      /**
       * <code>string dateFin = 2;</code>
       * @param value The bytes for dateFin to set.
       * @return This builder for chaining.
       */
      public Builder setDateFinBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        dateFin_ = value;
        onChanged();
        return this;
      }

      private int nbPersonne_ ;
      /**
       * <code>int32 nbPersonne = 3;</code>
       * @return The nbPersonne.
       */
      public int getNbPersonne() {
        return nbPersonne_;
      }
      /**
       * <code>int32 nbPersonne = 3;</code>
       * @param value The nbPersonne to set.
       * @return This builder for chaining.
       */
      public Builder setNbPersonne(int value) {
        
        nbPersonne_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 nbPersonne = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearNbPersonne() {
        
        nbPersonne_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ConsultRequest)
    }

    // @@protoc_insertion_point(class_scope:ConsultRequest)
    private static final org.isd.stubs.Consulteroffre.ConsultRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.isd.stubs.Consulteroffre.ConsultRequest();
    }

    public static org.isd.stubs.Consulteroffre.ConsultRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ConsultRequest>
        PARSER = new com.google.protobuf.AbstractParser<ConsultRequest>() {
      @java.lang.Override
      public ConsultRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ConsultRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ConsultRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ConsultRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.isd.stubs.Consulteroffre.ConsultRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface OffreDiponibleOrBuilder extends
      // @@protoc_insertion_point(interface_extends:OffreDiponible)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 idOffre = 1;</code>
     * @return The idOffre.
     */
    int getIdOffre();

    /**
     * <code>int32 typeChambre = 2;</code>
     * @return The typeChambre.
     */
    int getTypeChambre();

    /**
     * <code>string dateDisponibilite = 3;</code>
     * @return The dateDisponibilite.
     */
    java.lang.String getDateDisponibilite();
    /**
     * <code>string dateDisponibilite = 3;</code>
     * @return The bytes for dateDisponibilite.
     */
    com.google.protobuf.ByteString
        getDateDisponibiliteBytes();

    /**
     * <code>double prix = 4;</code>
     * @return The prix.
     */
    double getPrix();

    /**
     * <code>string imageUrl = 5;</code>
     * @return The imageUrl.
     */
    java.lang.String getImageUrl();
    /**
     * <code>string imageUrl = 5;</code>
     * @return The bytes for imageUrl.
     */
    com.google.protobuf.ByteString
        getImageUrlBytes();
  }
  /**
   * Protobuf type {@code OffreDiponible}
   */
  public  static final class OffreDiponible extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:OffreDiponible)
      OffreDiponibleOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use OffreDiponible.newBuilder() to construct.
    private OffreDiponible(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OffreDiponible() {
      dateDisponibilite_ = "";
      imageUrl_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new OffreDiponible();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private OffreDiponible(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              idOffre_ = input.readInt32();
              break;
            }
            case 16: {

              typeChambre_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              dateDisponibilite_ = s;
              break;
            }
            case 33: {

              prix_ = input.readDouble();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              imageUrl_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.isd.stubs.Consulteroffre.internal_static_OffreDiponible_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.isd.stubs.Consulteroffre.internal_static_OffreDiponible_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.isd.stubs.Consulteroffre.OffreDiponible.class, org.isd.stubs.Consulteroffre.OffreDiponible.Builder.class);
    }

    public static final int IDOFFRE_FIELD_NUMBER = 1;
    private int idOffre_;
    /**
     * <code>int32 idOffre = 1;</code>
     * @return The idOffre.
     */
    public int getIdOffre() {
      return idOffre_;
    }

    public static final int TYPECHAMBRE_FIELD_NUMBER = 2;
    private int typeChambre_;
    /**
     * <code>int32 typeChambre = 2;</code>
     * @return The typeChambre.
     */
    public int getTypeChambre() {
      return typeChambre_;
    }

    public static final int DATEDISPONIBILITE_FIELD_NUMBER = 3;
    private volatile java.lang.Object dateDisponibilite_;
    /**
     * <code>string dateDisponibilite = 3;</code>
     * @return The dateDisponibilite.
     */
    public java.lang.String getDateDisponibilite() {
      java.lang.Object ref = dateDisponibilite_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dateDisponibilite_ = s;
        return s;
      }
    }
    /**
     * <code>string dateDisponibilite = 3;</code>
     * @return The bytes for dateDisponibilite.
     */
    public com.google.protobuf.ByteString
        getDateDisponibiliteBytes() {
      java.lang.Object ref = dateDisponibilite_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dateDisponibilite_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRIX_FIELD_NUMBER = 4;
    private double prix_;
    /**
     * <code>double prix = 4;</code>
     * @return The prix.
     */
    public double getPrix() {
      return prix_;
    }

    public static final int IMAGEURL_FIELD_NUMBER = 5;
    private volatile java.lang.Object imageUrl_;
    /**
     * <code>string imageUrl = 5;</code>
     * @return The imageUrl.
     */
    public java.lang.String getImageUrl() {
      java.lang.Object ref = imageUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        imageUrl_ = s;
        return s;
      }
    }
    /**
     * <code>string imageUrl = 5;</code>
     * @return The bytes for imageUrl.
     */
    public com.google.protobuf.ByteString
        getImageUrlBytes() {
      java.lang.Object ref = imageUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        imageUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (idOffre_ != 0) {
        output.writeInt32(1, idOffre_);
      }
      if (typeChambre_ != 0) {
        output.writeInt32(2, typeChambre_);
      }
      if (!getDateDisponibiliteBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, dateDisponibilite_);
      }
      if (prix_ != 0D) {
        output.writeDouble(4, prix_);
      }
      if (!getImageUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, imageUrl_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (idOffre_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, idOffre_);
      }
      if (typeChambre_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, typeChambre_);
      }
      if (!getDateDisponibiliteBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, dateDisponibilite_);
      }
      if (prix_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, prix_);
      }
      if (!getImageUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, imageUrl_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.isd.stubs.Consulteroffre.OffreDiponible)) {
        return super.equals(obj);
      }
      org.isd.stubs.Consulteroffre.OffreDiponible other = (org.isd.stubs.Consulteroffre.OffreDiponible) obj;

      if (getIdOffre()
          != other.getIdOffre()) return false;
      if (getTypeChambre()
          != other.getTypeChambre()) return false;
      if (!getDateDisponibilite()
          .equals(other.getDateDisponibilite())) return false;
      if (java.lang.Double.doubleToLongBits(getPrix())
          != java.lang.Double.doubleToLongBits(
              other.getPrix())) return false;
      if (!getImageUrl()
          .equals(other.getImageUrl())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + IDOFFRE_FIELD_NUMBER;
      hash = (53 * hash) + getIdOffre();
      hash = (37 * hash) + TYPECHAMBRE_FIELD_NUMBER;
      hash = (53 * hash) + getTypeChambre();
      hash = (37 * hash) + DATEDISPONIBILITE_FIELD_NUMBER;
      hash = (53 * hash) + getDateDisponibilite().hashCode();
      hash = (37 * hash) + PRIX_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getPrix()));
      hash = (37 * hash) + IMAGEURL_FIELD_NUMBER;
      hash = (53 * hash) + getImageUrl().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.isd.stubs.Consulteroffre.OffreDiponible parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.isd.stubs.Consulteroffre.OffreDiponible parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.isd.stubs.Consulteroffre.OffreDiponible parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.isd.stubs.Consulteroffre.OffreDiponible parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.isd.stubs.Consulteroffre.OffreDiponible parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.isd.stubs.Consulteroffre.OffreDiponible parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.isd.stubs.Consulteroffre.OffreDiponible parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.isd.stubs.Consulteroffre.OffreDiponible parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.isd.stubs.Consulteroffre.OffreDiponible parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.isd.stubs.Consulteroffre.OffreDiponible parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.isd.stubs.Consulteroffre.OffreDiponible parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.isd.stubs.Consulteroffre.OffreDiponible parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.isd.stubs.Consulteroffre.OffreDiponible prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code OffreDiponible}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:OffreDiponible)
        org.isd.stubs.Consulteroffre.OffreDiponibleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.isd.stubs.Consulteroffre.internal_static_OffreDiponible_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.isd.stubs.Consulteroffre.internal_static_OffreDiponible_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.isd.stubs.Consulteroffre.OffreDiponible.class, org.isd.stubs.Consulteroffre.OffreDiponible.Builder.class);
      }

      // Construct using org.isd.stubs.Consulteroffre.OffreDiponible.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        idOffre_ = 0;

        typeChambre_ = 0;

        dateDisponibilite_ = "";

        prix_ = 0D;

        imageUrl_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.isd.stubs.Consulteroffre.internal_static_OffreDiponible_descriptor;
      }

      @java.lang.Override
      public org.isd.stubs.Consulteroffre.OffreDiponible getDefaultInstanceForType() {
        return org.isd.stubs.Consulteroffre.OffreDiponible.getDefaultInstance();
      }

      @java.lang.Override
      public org.isd.stubs.Consulteroffre.OffreDiponible build() {
        org.isd.stubs.Consulteroffre.OffreDiponible result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.isd.stubs.Consulteroffre.OffreDiponible buildPartial() {
        org.isd.stubs.Consulteroffre.OffreDiponible result = new org.isd.stubs.Consulteroffre.OffreDiponible(this);
        result.idOffre_ = idOffre_;
        result.typeChambre_ = typeChambre_;
        result.dateDisponibilite_ = dateDisponibilite_;
        result.prix_ = prix_;
        result.imageUrl_ = imageUrl_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.isd.stubs.Consulteroffre.OffreDiponible) {
          return mergeFrom((org.isd.stubs.Consulteroffre.OffreDiponible)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.isd.stubs.Consulteroffre.OffreDiponible other) {
        if (other == org.isd.stubs.Consulteroffre.OffreDiponible.getDefaultInstance()) return this;
        if (other.getIdOffre() != 0) {
          setIdOffre(other.getIdOffre());
        }
        if (other.getTypeChambre() != 0) {
          setTypeChambre(other.getTypeChambre());
        }
        if (!other.getDateDisponibilite().isEmpty()) {
          dateDisponibilite_ = other.dateDisponibilite_;
          onChanged();
        }
        if (other.getPrix() != 0D) {
          setPrix(other.getPrix());
        }
        if (!other.getImageUrl().isEmpty()) {
          imageUrl_ = other.imageUrl_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.isd.stubs.Consulteroffre.OffreDiponible parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.isd.stubs.Consulteroffre.OffreDiponible) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int idOffre_ ;
      /**
       * <code>int32 idOffre = 1;</code>
       * @return The idOffre.
       */
      public int getIdOffre() {
        return idOffre_;
      }
      /**
       * <code>int32 idOffre = 1;</code>
       * @param value The idOffre to set.
       * @return This builder for chaining.
       */
      public Builder setIdOffre(int value) {
        
        idOffre_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 idOffre = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIdOffre() {
        
        idOffre_ = 0;
        onChanged();
        return this;
      }

      private int typeChambre_ ;
      /**
       * <code>int32 typeChambre = 2;</code>
       * @return The typeChambre.
       */
      public int getTypeChambre() {
        return typeChambre_;
      }
      /**
       * <code>int32 typeChambre = 2;</code>
       * @param value The typeChambre to set.
       * @return This builder for chaining.
       */
      public Builder setTypeChambre(int value) {
        
        typeChambre_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 typeChambre = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTypeChambre() {
        
        typeChambre_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object dateDisponibilite_ = "";
      /**
       * <code>string dateDisponibilite = 3;</code>
       * @return The dateDisponibilite.
       */
      public java.lang.String getDateDisponibilite() {
        java.lang.Object ref = dateDisponibilite_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          dateDisponibilite_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string dateDisponibilite = 3;</code>
       * @return The bytes for dateDisponibilite.
       */
      public com.google.protobuf.ByteString
          getDateDisponibiliteBytes() {
        java.lang.Object ref = dateDisponibilite_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dateDisponibilite_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string dateDisponibilite = 3;</code>
       * @param value The dateDisponibilite to set.
       * @return This builder for chaining.
       */
      public Builder setDateDisponibilite(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        dateDisponibilite_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string dateDisponibilite = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDateDisponibilite() {
        
        dateDisponibilite_ = getDefaultInstance().getDateDisponibilite();
        onChanged();
        return this;
      }
      /**
       * <code>string dateDisponibilite = 3;</code>
       * @param value The bytes for dateDisponibilite to set.
       * @return This builder for chaining.
       */
      public Builder setDateDisponibiliteBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        dateDisponibilite_ = value;
        onChanged();
        return this;
      }

      private double prix_ ;
      /**
       * <code>double prix = 4;</code>
       * @return The prix.
       */
      public double getPrix() {
        return prix_;
      }
      /**
       * <code>double prix = 4;</code>
       * @param value The prix to set.
       * @return This builder for chaining.
       */
      public Builder setPrix(double value) {
        
        prix_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double prix = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearPrix() {
        
        prix_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object imageUrl_ = "";
      /**
       * <code>string imageUrl = 5;</code>
       * @return The imageUrl.
       */
      public java.lang.String getImageUrl() {
        java.lang.Object ref = imageUrl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          imageUrl_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string imageUrl = 5;</code>
       * @return The bytes for imageUrl.
       */
      public com.google.protobuf.ByteString
          getImageUrlBytes() {
        java.lang.Object ref = imageUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          imageUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string imageUrl = 5;</code>
       * @param value The imageUrl to set.
       * @return This builder for chaining.
       */
      public Builder setImageUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        imageUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string imageUrl = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearImageUrl() {
        
        imageUrl_ = getDefaultInstance().getImageUrl();
        onChanged();
        return this;
      }
      /**
       * <code>string imageUrl = 5;</code>
       * @param value The bytes for imageUrl to set.
       * @return This builder for chaining.
       */
      public Builder setImageUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        imageUrl_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:OffreDiponible)
    }

    // @@protoc_insertion_point(class_scope:OffreDiponible)
    private static final org.isd.stubs.Consulteroffre.OffreDiponible DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.isd.stubs.Consulteroffre.OffreDiponible();
    }

    public static org.isd.stubs.Consulteroffre.OffreDiponible getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OffreDiponible>
        PARSER = new com.google.protobuf.AbstractParser<OffreDiponible>() {
      @java.lang.Override
      public OffreDiponible parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OffreDiponible(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OffreDiponible> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OffreDiponible> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.isd.stubs.Consulteroffre.OffreDiponible getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ConsultResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ConsultResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .OffreDiponible offres = 1;</code>
     */
    java.util.List<org.isd.stubs.Consulteroffre.OffreDiponible> 
        getOffresList();
    /**
     * <code>repeated .OffreDiponible offres = 1;</code>
     */
    org.isd.stubs.Consulteroffre.OffreDiponible getOffres(int index);
    /**
     * <code>repeated .OffreDiponible offres = 1;</code>
     */
    int getOffresCount();
    /**
     * <code>repeated .OffreDiponible offres = 1;</code>
     */
    java.util.List<? extends org.isd.stubs.Consulteroffre.OffreDiponibleOrBuilder> 
        getOffresOrBuilderList();
    /**
     * <code>repeated .OffreDiponible offres = 1;</code>
     */
    org.isd.stubs.Consulteroffre.OffreDiponibleOrBuilder getOffresOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ConsultResponse}
   */
  public  static final class ConsultResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ConsultResponse)
      ConsultResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ConsultResponse.newBuilder() to construct.
    private ConsultResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ConsultResponse() {
      offres_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ConsultResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ConsultResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                offres_ = new java.util.ArrayList<org.isd.stubs.Consulteroffre.OffreDiponible>();
                mutable_bitField0_ |= 0x00000001;
              }
              offres_.add(
                  input.readMessage(org.isd.stubs.Consulteroffre.OffreDiponible.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          offres_ = java.util.Collections.unmodifiableList(offres_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.isd.stubs.Consulteroffre.internal_static_ConsultResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.isd.stubs.Consulteroffre.internal_static_ConsultResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.isd.stubs.Consulteroffre.ConsultResponse.class, org.isd.stubs.Consulteroffre.ConsultResponse.Builder.class);
    }

    public static final int OFFRES_FIELD_NUMBER = 1;
    private java.util.List<org.isd.stubs.Consulteroffre.OffreDiponible> offres_;
    /**
     * <code>repeated .OffreDiponible offres = 1;</code>
     */
    public java.util.List<org.isd.stubs.Consulteroffre.OffreDiponible> getOffresList() {
      return offres_;
    }
    /**
     * <code>repeated .OffreDiponible offres = 1;</code>
     */
    public java.util.List<? extends org.isd.stubs.Consulteroffre.OffreDiponibleOrBuilder> 
        getOffresOrBuilderList() {
      return offres_;
    }
    /**
     * <code>repeated .OffreDiponible offres = 1;</code>
     */
    public int getOffresCount() {
      return offres_.size();
    }
    /**
     * <code>repeated .OffreDiponible offres = 1;</code>
     */
    public org.isd.stubs.Consulteroffre.OffreDiponible getOffres(int index) {
      return offres_.get(index);
    }
    /**
     * <code>repeated .OffreDiponible offres = 1;</code>
     */
    public org.isd.stubs.Consulteroffre.OffreDiponibleOrBuilder getOffresOrBuilder(
        int index) {
      return offres_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < offres_.size(); i++) {
        output.writeMessage(1, offres_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < offres_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, offres_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.isd.stubs.Consulteroffre.ConsultResponse)) {
        return super.equals(obj);
      }
      org.isd.stubs.Consulteroffre.ConsultResponse other = (org.isd.stubs.Consulteroffre.ConsultResponse) obj;

      if (!getOffresList()
          .equals(other.getOffresList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getOffresCount() > 0) {
        hash = (37 * hash) + OFFRES_FIELD_NUMBER;
        hash = (53 * hash) + getOffresList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.isd.stubs.Consulteroffre.ConsultResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.isd.stubs.Consulteroffre.ConsultResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.isd.stubs.Consulteroffre.ConsultResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.isd.stubs.Consulteroffre.ConsultResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.isd.stubs.Consulteroffre.ConsultResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.isd.stubs.Consulteroffre.ConsultResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.isd.stubs.Consulteroffre.ConsultResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.isd.stubs.Consulteroffre.ConsultResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.isd.stubs.Consulteroffre.ConsultResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.isd.stubs.Consulteroffre.ConsultResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.isd.stubs.Consulteroffre.ConsultResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.isd.stubs.Consulteroffre.ConsultResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.isd.stubs.Consulteroffre.ConsultResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ConsultResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ConsultResponse)
        org.isd.stubs.Consulteroffre.ConsultResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.isd.stubs.Consulteroffre.internal_static_ConsultResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.isd.stubs.Consulteroffre.internal_static_ConsultResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.isd.stubs.Consulteroffre.ConsultResponse.class, org.isd.stubs.Consulteroffre.ConsultResponse.Builder.class);
      }

      // Construct using org.isd.stubs.Consulteroffre.ConsultResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getOffresFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (offresBuilder_ == null) {
          offres_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          offresBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.isd.stubs.Consulteroffre.internal_static_ConsultResponse_descriptor;
      }

      @java.lang.Override
      public org.isd.stubs.Consulteroffre.ConsultResponse getDefaultInstanceForType() {
        return org.isd.stubs.Consulteroffre.ConsultResponse.getDefaultInstance();
      }

      @java.lang.Override
      public org.isd.stubs.Consulteroffre.ConsultResponse build() {
        org.isd.stubs.Consulteroffre.ConsultResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.isd.stubs.Consulteroffre.ConsultResponse buildPartial() {
        org.isd.stubs.Consulteroffre.ConsultResponse result = new org.isd.stubs.Consulteroffre.ConsultResponse(this);
        int from_bitField0_ = bitField0_;
        if (offresBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            offres_ = java.util.Collections.unmodifiableList(offres_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.offres_ = offres_;
        } else {
          result.offres_ = offresBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.isd.stubs.Consulteroffre.ConsultResponse) {
          return mergeFrom((org.isd.stubs.Consulteroffre.ConsultResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.isd.stubs.Consulteroffre.ConsultResponse other) {
        if (other == org.isd.stubs.Consulteroffre.ConsultResponse.getDefaultInstance()) return this;
        if (offresBuilder_ == null) {
          if (!other.offres_.isEmpty()) {
            if (offres_.isEmpty()) {
              offres_ = other.offres_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureOffresIsMutable();
              offres_.addAll(other.offres_);
            }
            onChanged();
          }
        } else {
          if (!other.offres_.isEmpty()) {
            if (offresBuilder_.isEmpty()) {
              offresBuilder_.dispose();
              offresBuilder_ = null;
              offres_ = other.offres_;
              bitField0_ = (bitField0_ & ~0x00000001);
              offresBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getOffresFieldBuilder() : null;
            } else {
              offresBuilder_.addAllMessages(other.offres_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.isd.stubs.Consulteroffre.ConsultResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.isd.stubs.Consulteroffre.ConsultResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<org.isd.stubs.Consulteroffre.OffreDiponible> offres_ =
        java.util.Collections.emptyList();
      private void ensureOffresIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          offres_ = new java.util.ArrayList<org.isd.stubs.Consulteroffre.OffreDiponible>(offres_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.isd.stubs.Consulteroffre.OffreDiponible, org.isd.stubs.Consulteroffre.OffreDiponible.Builder, org.isd.stubs.Consulteroffre.OffreDiponibleOrBuilder> offresBuilder_;

      /**
       * <code>repeated .OffreDiponible offres = 1;</code>
       */
      public java.util.List<org.isd.stubs.Consulteroffre.OffreDiponible> getOffresList() {
        if (offresBuilder_ == null) {
          return java.util.Collections.unmodifiableList(offres_);
        } else {
          return offresBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .OffreDiponible offres = 1;</code>
       */
      public int getOffresCount() {
        if (offresBuilder_ == null) {
          return offres_.size();
        } else {
          return offresBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .OffreDiponible offres = 1;</code>
       */
      public org.isd.stubs.Consulteroffre.OffreDiponible getOffres(int index) {
        if (offresBuilder_ == null) {
          return offres_.get(index);
        } else {
          return offresBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .OffreDiponible offres = 1;</code>
       */
      public Builder setOffres(
          int index, org.isd.stubs.Consulteroffre.OffreDiponible value) {
        if (offresBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOffresIsMutable();
          offres_.set(index, value);
          onChanged();
        } else {
          offresBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .OffreDiponible offres = 1;</code>
       */
      public Builder setOffres(
          int index, org.isd.stubs.Consulteroffre.OffreDiponible.Builder builderForValue) {
        if (offresBuilder_ == null) {
          ensureOffresIsMutable();
          offres_.set(index, builderForValue.build());
          onChanged();
        } else {
          offresBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .OffreDiponible offres = 1;</code>
       */
      public Builder addOffres(org.isd.stubs.Consulteroffre.OffreDiponible value) {
        if (offresBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOffresIsMutable();
          offres_.add(value);
          onChanged();
        } else {
          offresBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .OffreDiponible offres = 1;</code>
       */
      public Builder addOffres(
          int index, org.isd.stubs.Consulteroffre.OffreDiponible value) {
        if (offresBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOffresIsMutable();
          offres_.add(index, value);
          onChanged();
        } else {
          offresBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .OffreDiponible offres = 1;</code>
       */
      public Builder addOffres(
          org.isd.stubs.Consulteroffre.OffreDiponible.Builder builderForValue) {
        if (offresBuilder_ == null) {
          ensureOffresIsMutable();
          offres_.add(builderForValue.build());
          onChanged();
        } else {
          offresBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .OffreDiponible offres = 1;</code>
       */
      public Builder addOffres(
          int index, org.isd.stubs.Consulteroffre.OffreDiponible.Builder builderForValue) {
        if (offresBuilder_ == null) {
          ensureOffresIsMutable();
          offres_.add(index, builderForValue.build());
          onChanged();
        } else {
          offresBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .OffreDiponible offres = 1;</code>
       */
      public Builder addAllOffres(
          java.lang.Iterable<? extends org.isd.stubs.Consulteroffre.OffreDiponible> values) {
        if (offresBuilder_ == null) {
          ensureOffresIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, offres_);
          onChanged();
        } else {
          offresBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .OffreDiponible offres = 1;</code>
       */
      public Builder clearOffres() {
        if (offresBuilder_ == null) {
          offres_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          offresBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .OffreDiponible offres = 1;</code>
       */
      public Builder removeOffres(int index) {
        if (offresBuilder_ == null) {
          ensureOffresIsMutable();
          offres_.remove(index);
          onChanged();
        } else {
          offresBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .OffreDiponible offres = 1;</code>
       */
      public org.isd.stubs.Consulteroffre.OffreDiponible.Builder getOffresBuilder(
          int index) {
        return getOffresFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .OffreDiponible offres = 1;</code>
       */
      public org.isd.stubs.Consulteroffre.OffreDiponibleOrBuilder getOffresOrBuilder(
          int index) {
        if (offresBuilder_ == null) {
          return offres_.get(index);  } else {
          return offresBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .OffreDiponible offres = 1;</code>
       */
      public java.util.List<? extends org.isd.stubs.Consulteroffre.OffreDiponibleOrBuilder> 
           getOffresOrBuilderList() {
        if (offresBuilder_ != null) {
          return offresBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(offres_);
        }
      }
      /**
       * <code>repeated .OffreDiponible offres = 1;</code>
       */
      public org.isd.stubs.Consulteroffre.OffreDiponible.Builder addOffresBuilder() {
        return getOffresFieldBuilder().addBuilder(
            org.isd.stubs.Consulteroffre.OffreDiponible.getDefaultInstance());
      }
      /**
       * <code>repeated .OffreDiponible offres = 1;</code>
       */
      public org.isd.stubs.Consulteroffre.OffreDiponible.Builder addOffresBuilder(
          int index) {
        return getOffresFieldBuilder().addBuilder(
            index, org.isd.stubs.Consulteroffre.OffreDiponible.getDefaultInstance());
      }
      /**
       * <code>repeated .OffreDiponible offres = 1;</code>
       */
      public java.util.List<org.isd.stubs.Consulteroffre.OffreDiponible.Builder> 
           getOffresBuilderList() {
        return getOffresFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.isd.stubs.Consulteroffre.OffreDiponible, org.isd.stubs.Consulteroffre.OffreDiponible.Builder, org.isd.stubs.Consulteroffre.OffreDiponibleOrBuilder> 
          getOffresFieldBuilder() {
        if (offresBuilder_ == null) {
          offresBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              org.isd.stubs.Consulteroffre.OffreDiponible, org.isd.stubs.Consulteroffre.OffreDiponible.Builder, org.isd.stubs.Consulteroffre.OffreDiponibleOrBuilder>(
                  offres_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          offres_ = null;
        }
        return offresBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ConsultResponse)
    }

    // @@protoc_insertion_point(class_scope:ConsultResponse)
    private static final org.isd.stubs.Consulteroffre.ConsultResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.isd.stubs.Consulteroffre.ConsultResponse();
    }

    public static org.isd.stubs.Consulteroffre.ConsultResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ConsultResponse>
        PARSER = new com.google.protobuf.AbstractParser<ConsultResponse>() {
      @java.lang.Override
      public ConsultResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ConsultResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ConsultResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ConsultResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.isd.stubs.Consulteroffre.ConsultResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ConsultRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ConsultRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OffreDiponible_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OffreDiponible_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ConsultResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ConsultResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024consulteroffre.proto\"H\n\016ConsultRequest" +
      "\022\021\n\tdateDebut\030\001 \001(\t\022\017\n\007dateFin\030\002 \001(\t\022\022\n\n" +
      "nbPersonne\030\003 \001(\005\"q\n\016OffreDiponible\022\017\n\007id" +
      "Offre\030\001 \001(\005\022\023\n\013typeChambre\030\002 \001(\005\022\031\n\021date" +
      "Disponibilite\030\003 \001(\t\022\014\n\004prix\030\004 \001(\001\022\020\n\010ima" +
      "geUrl\030\005 \001(\t\"2\n\017ConsultResponse\022\037\n\006offres" +
      "\030\001 \003(\0132\017.OffreDiponible2U\n\025HotelServiceC" +
      "onsulter\022<\n\027consulterDisponibilites\022\017.Co" +
      "nsultRequest\032\020.ConsultResponseB\017\n\rorg.is" +
      "d.stubsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ConsultRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ConsultRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ConsultRequest_descriptor,
        new java.lang.String[] { "DateDebut", "DateFin", "NbPersonne", });
    internal_static_OffreDiponible_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_OffreDiponible_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OffreDiponible_descriptor,
        new java.lang.String[] { "IdOffre", "TypeChambre", "DateDisponibilite", "Prix", "ImageUrl", });
    internal_static_ConsultResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ConsultResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ConsultResponse_descriptor,
        new java.lang.String[] { "Offres", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
