// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reserverchambre.proto

package org.isd.stubs;

public final class Reserverchambre {
  private Reserverchambre() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ReserverRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ReserverRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 idOffre = 1;</code>
     * @return The idOffre.
     */
    int getIdOffre();

    /**
     * <code>string prenom = 2;</code>
     * @return The prenom.
     */
    java.lang.String getPrenom();
    /**
     * <code>string prenom = 2;</code>
     * @return The bytes for prenom.
     */
    com.google.protobuf.ByteString
        getPrenomBytes();

    /**
     * <code>string nom = 3;</code>
     * @return The nom.
     */
    java.lang.String getNom();
    /**
     * <code>string nom = 3;</code>
     * @return The bytes for nom.
     */
    com.google.protobuf.ByteString
        getNomBytes();

    /**
     * <code>string email = 4;</code>
     * @return The email.
     */
    java.lang.String getEmail();
    /**
     * <code>string email = 4;</code>
     * @return The bytes for email.
     */
    com.google.protobuf.ByteString
        getEmailBytes();
  }
  /**
   * Protobuf type {@code ReserverRequest}
   */
  public  static final class ReserverRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ReserverRequest)
      ReserverRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ReserverRequest.newBuilder() to construct.
    private ReserverRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ReserverRequest() {
      prenom_ = "";
      nom_ = "";
      email_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ReserverRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ReserverRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              idOffre_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              prenom_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              nom_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              email_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.isd.stubs.Reserverchambre.internal_static_ReserverRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.isd.stubs.Reserverchambre.internal_static_ReserverRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.isd.stubs.Reserverchambre.ReserverRequest.class, org.isd.stubs.Reserverchambre.ReserverRequest.Builder.class);
    }

    public static final int IDOFFRE_FIELD_NUMBER = 1;
    private int idOffre_;
    /**
     * <code>int32 idOffre = 1;</code>
     * @return The idOffre.
     */
    public int getIdOffre() {
      return idOffre_;
    }

    public static final int PRENOM_FIELD_NUMBER = 2;
    private volatile java.lang.Object prenom_;
    /**
     * <code>string prenom = 2;</code>
     * @return The prenom.
     */
    public java.lang.String getPrenom() {
      java.lang.Object ref = prenom_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        prenom_ = s;
        return s;
      }
    }
    /**
     * <code>string prenom = 2;</code>
     * @return The bytes for prenom.
     */
    public com.google.protobuf.ByteString
        getPrenomBytes() {
      java.lang.Object ref = prenom_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        prenom_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NOM_FIELD_NUMBER = 3;
    private volatile java.lang.Object nom_;
    /**
     * <code>string nom = 3;</code>
     * @return The nom.
     */
    public java.lang.String getNom() {
      java.lang.Object ref = nom_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nom_ = s;
        return s;
      }
    }
    /**
     * <code>string nom = 3;</code>
     * @return The bytes for nom.
     */
    public com.google.protobuf.ByteString
        getNomBytes() {
      java.lang.Object ref = nom_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nom_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAIL_FIELD_NUMBER = 4;
    private volatile java.lang.Object email_;
    /**
     * <code>string email = 4;</code>
     * @return The email.
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      }
    }
    /**
     * <code>string email = 4;</code>
     * @return The bytes for email.
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (idOffre_ != 0) {
        output.writeInt32(1, idOffre_);
      }
      if (!getPrenomBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, prenom_);
      }
      if (!getNomBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, nom_);
      }
      if (!getEmailBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, email_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (idOffre_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, idOffre_);
      }
      if (!getPrenomBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, prenom_);
      }
      if (!getNomBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, nom_);
      }
      if (!getEmailBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, email_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.isd.stubs.Reserverchambre.ReserverRequest)) {
        return super.equals(obj);
      }
      org.isd.stubs.Reserverchambre.ReserverRequest other = (org.isd.stubs.Reserverchambre.ReserverRequest) obj;

      if (getIdOffre()
          != other.getIdOffre()) return false;
      if (!getPrenom()
          .equals(other.getPrenom())) return false;
      if (!getNom()
          .equals(other.getNom())) return false;
      if (!getEmail()
          .equals(other.getEmail())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + IDOFFRE_FIELD_NUMBER;
      hash = (53 * hash) + getIdOffre();
      hash = (37 * hash) + PRENOM_FIELD_NUMBER;
      hash = (53 * hash) + getPrenom().hashCode();
      hash = (37 * hash) + NOM_FIELD_NUMBER;
      hash = (53 * hash) + getNom().hashCode();
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.isd.stubs.Reserverchambre.ReserverRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.isd.stubs.Reserverchambre.ReserverRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.isd.stubs.Reserverchambre.ReserverRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.isd.stubs.Reserverchambre.ReserverRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.isd.stubs.Reserverchambre.ReserverRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.isd.stubs.Reserverchambre.ReserverRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.isd.stubs.Reserverchambre.ReserverRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.isd.stubs.Reserverchambre.ReserverRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.isd.stubs.Reserverchambre.ReserverRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.isd.stubs.Reserverchambre.ReserverRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.isd.stubs.Reserverchambre.ReserverRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.isd.stubs.Reserverchambre.ReserverRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.isd.stubs.Reserverchambre.ReserverRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ReserverRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ReserverRequest)
        org.isd.stubs.Reserverchambre.ReserverRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.isd.stubs.Reserverchambre.internal_static_ReserverRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.isd.stubs.Reserverchambre.internal_static_ReserverRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.isd.stubs.Reserverchambre.ReserverRequest.class, org.isd.stubs.Reserverchambre.ReserverRequest.Builder.class);
      }

      // Construct using org.isd.stubs.Reserverchambre.ReserverRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        idOffre_ = 0;

        prenom_ = "";

        nom_ = "";

        email_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.isd.stubs.Reserverchambre.internal_static_ReserverRequest_descriptor;
      }

      @java.lang.Override
      public org.isd.stubs.Reserverchambre.ReserverRequest getDefaultInstanceForType() {
        return org.isd.stubs.Reserverchambre.ReserverRequest.getDefaultInstance();
      }

      @java.lang.Override
      public org.isd.stubs.Reserverchambre.ReserverRequest build() {
        org.isd.stubs.Reserverchambre.ReserverRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.isd.stubs.Reserverchambre.ReserverRequest buildPartial() {
        org.isd.stubs.Reserverchambre.ReserverRequest result = new org.isd.stubs.Reserverchambre.ReserverRequest(this);
        result.idOffre_ = idOffre_;
        result.prenom_ = prenom_;
        result.nom_ = nom_;
        result.email_ = email_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.isd.stubs.Reserverchambre.ReserverRequest) {
          return mergeFrom((org.isd.stubs.Reserverchambre.ReserverRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.isd.stubs.Reserverchambre.ReserverRequest other) {
        if (other == org.isd.stubs.Reserverchambre.ReserverRequest.getDefaultInstance()) return this;
        if (other.getIdOffre() != 0) {
          setIdOffre(other.getIdOffre());
        }
        if (!other.getPrenom().isEmpty()) {
          prenom_ = other.prenom_;
          onChanged();
        }
        if (!other.getNom().isEmpty()) {
          nom_ = other.nom_;
          onChanged();
        }
        if (!other.getEmail().isEmpty()) {
          email_ = other.email_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.isd.stubs.Reserverchambre.ReserverRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.isd.stubs.Reserverchambre.ReserverRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int idOffre_ ;
      /**
       * <code>int32 idOffre = 1;</code>
       * @return The idOffre.
       */
      public int getIdOffre() {
        return idOffre_;
      }
      /**
       * <code>int32 idOffre = 1;</code>
       * @param value The idOffre to set.
       * @return This builder for chaining.
       */
      public Builder setIdOffre(int value) {
        
        idOffre_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 idOffre = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIdOffre() {
        
        idOffre_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object prenom_ = "";
      /**
       * <code>string prenom = 2;</code>
       * @return The prenom.
       */
      public java.lang.String getPrenom() {
        java.lang.Object ref = prenom_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          prenom_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string prenom = 2;</code>
       * @return The bytes for prenom.
       */
      public com.google.protobuf.ByteString
          getPrenomBytes() {
        java.lang.Object ref = prenom_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          prenom_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string prenom = 2;</code>
       * @param value The prenom to set.
       * @return This builder for chaining.
       */
      public Builder setPrenom(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        prenom_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string prenom = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPrenom() {
        
        prenom_ = getDefaultInstance().getPrenom();
        onChanged();
        return this;
      }
      /**
       * <code>string prenom = 2;</code>
       * @param value The bytes for prenom to set.
       * @return This builder for chaining.
       */
      public Builder setPrenomBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        prenom_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object nom_ = "";
      /**
       * <code>string nom = 3;</code>
       * @return The nom.
       */
      public java.lang.String getNom() {
        java.lang.Object ref = nom_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nom_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string nom = 3;</code>
       * @return The bytes for nom.
       */
      public com.google.protobuf.ByteString
          getNomBytes() {
        java.lang.Object ref = nom_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nom_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nom = 3;</code>
       * @param value The nom to set.
       * @return This builder for chaining.
       */
      public Builder setNom(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nom_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string nom = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearNom() {
        
        nom_ = getDefaultInstance().getNom();
        onChanged();
        return this;
      }
      /**
       * <code>string nom = 3;</code>
       * @param value The bytes for nom to set.
       * @return This builder for chaining.
       */
      public Builder setNomBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nom_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>string email = 4;</code>
       * @return The email.
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string email = 4;</code>
       * @return The bytes for email.
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string email = 4;</code>
       * @param value The email to set.
       * @return This builder for chaining.
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string email = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmail() {
        
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>string email = 4;</code>
       * @param value The bytes for email to set.
       * @return This builder for chaining.
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        email_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ReserverRequest)
    }

    // @@protoc_insertion_point(class_scope:ReserverRequest)
    private static final org.isd.stubs.Reserverchambre.ReserverRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.isd.stubs.Reserverchambre.ReserverRequest();
    }

    public static org.isd.stubs.Reserverchambre.ReserverRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReserverRequest>
        PARSER = new com.google.protobuf.AbstractParser<ReserverRequest>() {
      @java.lang.Override
      public ReserverRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReserverRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ReserverRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ReserverRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.isd.stubs.Reserverchambre.ReserverRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ReservationResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ReservationResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool success = 1;</code>
     * @return The success.
     */
    boolean getSuccess();

    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    java.lang.String getMessage();
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <code>string reservationReference = 3;</code>
     * @return The reservationReference.
     */
    java.lang.String getReservationReference();
    /**
     * <code>string reservationReference = 3;</code>
     * @return The bytes for reservationReference.
     */
    com.google.protobuf.ByteString
        getReservationReferenceBytes();
  }
  /**
   * Protobuf type {@code ReservationResponse}
   */
  public  static final class ReservationResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ReservationResponse)
      ReservationResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ReservationResponse.newBuilder() to construct.
    private ReservationResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ReservationResponse() {
      message_ = "";
      reservationReference_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ReservationResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ReservationResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              success_ = input.readBool();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              reservationReference_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.isd.stubs.Reserverchambre.internal_static_ReservationResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.isd.stubs.Reserverchambre.internal_static_ReservationResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.isd.stubs.Reserverchambre.ReservationResponse.class, org.isd.stubs.Reserverchambre.ReservationResponse.Builder.class);
    }

    public static final int SUCCESS_FIELD_NUMBER = 1;
    private boolean success_;
    /**
     * <code>bool success = 1;</code>
     * @return The success.
     */
    public boolean getSuccess() {
      return success_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    private volatile java.lang.Object message_;
    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESERVATIONREFERENCE_FIELD_NUMBER = 3;
    private volatile java.lang.Object reservationReference_;
    /**
     * <code>string reservationReference = 3;</code>
     * @return The reservationReference.
     */
    public java.lang.String getReservationReference() {
      java.lang.Object ref = reservationReference_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reservationReference_ = s;
        return s;
      }
    }
    /**
     * <code>string reservationReference = 3;</code>
     * @return The bytes for reservationReference.
     */
    public com.google.protobuf.ByteString
        getReservationReferenceBytes() {
      java.lang.Object ref = reservationReference_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reservationReference_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (success_ != false) {
        output.writeBool(1, success_);
      }
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
      }
      if (!getReservationReferenceBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, reservationReference_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (success_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, success_);
      }
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
      }
      if (!getReservationReferenceBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, reservationReference_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.isd.stubs.Reserverchambre.ReservationResponse)) {
        return super.equals(obj);
      }
      org.isd.stubs.Reserverchambre.ReservationResponse other = (org.isd.stubs.Reserverchambre.ReservationResponse) obj;

      if (getSuccess()
          != other.getSuccess()) return false;
      if (!getMessage()
          .equals(other.getMessage())) return false;
      if (!getReservationReference()
          .equals(other.getReservationReference())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSuccess());
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (37 * hash) + RESERVATIONREFERENCE_FIELD_NUMBER;
      hash = (53 * hash) + getReservationReference().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.isd.stubs.Reserverchambre.ReservationResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.isd.stubs.Reserverchambre.ReservationResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.isd.stubs.Reserverchambre.ReservationResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.isd.stubs.Reserverchambre.ReservationResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.isd.stubs.Reserverchambre.ReservationResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.isd.stubs.Reserverchambre.ReservationResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.isd.stubs.Reserverchambre.ReservationResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.isd.stubs.Reserverchambre.ReservationResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.isd.stubs.Reserverchambre.ReservationResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.isd.stubs.Reserverchambre.ReservationResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.isd.stubs.Reserverchambre.ReservationResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.isd.stubs.Reserverchambre.ReservationResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.isd.stubs.Reserverchambre.ReservationResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ReservationResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ReservationResponse)
        org.isd.stubs.Reserverchambre.ReservationResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.isd.stubs.Reserverchambre.internal_static_ReservationResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.isd.stubs.Reserverchambre.internal_static_ReservationResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.isd.stubs.Reserverchambre.ReservationResponse.class, org.isd.stubs.Reserverchambre.ReservationResponse.Builder.class);
      }

      // Construct using org.isd.stubs.Reserverchambre.ReservationResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        success_ = false;

        message_ = "";

        reservationReference_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.isd.stubs.Reserverchambre.internal_static_ReservationResponse_descriptor;
      }

      @java.lang.Override
      public org.isd.stubs.Reserverchambre.ReservationResponse getDefaultInstanceForType() {
        return org.isd.stubs.Reserverchambre.ReservationResponse.getDefaultInstance();
      }

      @java.lang.Override
      public org.isd.stubs.Reserverchambre.ReservationResponse build() {
        org.isd.stubs.Reserverchambre.ReservationResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.isd.stubs.Reserverchambre.ReservationResponse buildPartial() {
        org.isd.stubs.Reserverchambre.ReservationResponse result = new org.isd.stubs.Reserverchambre.ReservationResponse(this);
        result.success_ = success_;
        result.message_ = message_;
        result.reservationReference_ = reservationReference_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.isd.stubs.Reserverchambre.ReservationResponse) {
          return mergeFrom((org.isd.stubs.Reserverchambre.ReservationResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.isd.stubs.Reserverchambre.ReservationResponse other) {
        if (other == org.isd.stubs.Reserverchambre.ReservationResponse.getDefaultInstance()) return this;
        if (other.getSuccess() != false) {
          setSuccess(other.getSuccess());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        if (!other.getReservationReference().isEmpty()) {
          reservationReference_ = other.reservationReference_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.isd.stubs.Reserverchambre.ReservationResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.isd.stubs.Reserverchambre.ReservationResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean success_ ;
      /**
       * <code>bool success = 1;</code>
       * @return The success.
       */
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <code>bool success = 1;</code>
       * @param value The success to set.
       * @return This builder for chaining.
       */
      public Builder setSuccess(boolean value) {
        
        success_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool success = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSuccess() {
        
        success_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>string message = 2;</code>
       * @return The message.
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string message = 2;</code>
       * @return The bytes for message.
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string message = 2;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object reservationReference_ = "";
      /**
       * <code>string reservationReference = 3;</code>
       * @return The reservationReference.
       */
      public java.lang.String getReservationReference() {
        java.lang.Object ref = reservationReference_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          reservationReference_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string reservationReference = 3;</code>
       * @return The bytes for reservationReference.
       */
      public com.google.protobuf.ByteString
          getReservationReferenceBytes() {
        java.lang.Object ref = reservationReference_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          reservationReference_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string reservationReference = 3;</code>
       * @param value The reservationReference to set.
       * @return This builder for chaining.
       */
      public Builder setReservationReference(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        reservationReference_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string reservationReference = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearReservationReference() {
        
        reservationReference_ = getDefaultInstance().getReservationReference();
        onChanged();
        return this;
      }
      /**
       * <code>string reservationReference = 3;</code>
       * @param value The bytes for reservationReference to set.
       * @return This builder for chaining.
       */
      public Builder setReservationReferenceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        reservationReference_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ReservationResponse)
    }

    // @@protoc_insertion_point(class_scope:ReservationResponse)
    private static final org.isd.stubs.Reserverchambre.ReservationResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.isd.stubs.Reserverchambre.ReservationResponse();
    }

    public static org.isd.stubs.Reserverchambre.ReservationResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReservationResponse>
        PARSER = new com.google.protobuf.AbstractParser<ReservationResponse>() {
      @java.lang.Override
      public ReservationResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReservationResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ReservationResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ReservationResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.isd.stubs.Reserverchambre.ReservationResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ReserverResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ReserverResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.ReservationResponse reservationReservation = 1;</code>
     * @return Whether the reservationReservation field is set.
     */
    boolean hasReservationReservation();
    /**
     * <code>.ReservationResponse reservationReservation = 1;</code>
     * @return The reservationReservation.
     */
    org.isd.stubs.Reserverchambre.ReservationResponse getReservationReservation();
    /**
     * <code>.ReservationResponse reservationReservation = 1;</code>
     */
    org.isd.stubs.Reserverchambre.ReservationResponseOrBuilder getReservationReservationOrBuilder();
  }
  /**
   * Protobuf type {@code ReserverResponse}
   */
  public  static final class ReserverResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ReserverResponse)
      ReserverResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ReserverResponse.newBuilder() to construct.
    private ReserverResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ReserverResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ReserverResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ReserverResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              org.isd.stubs.Reserverchambre.ReservationResponse.Builder subBuilder = null;
              if (reservationReservation_ != null) {
                subBuilder = reservationReservation_.toBuilder();
              }
              reservationReservation_ = input.readMessage(org.isd.stubs.Reserverchambre.ReservationResponse.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(reservationReservation_);
                reservationReservation_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.isd.stubs.Reserverchambre.internal_static_ReserverResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.isd.stubs.Reserverchambre.internal_static_ReserverResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.isd.stubs.Reserverchambre.ReserverResponse.class, org.isd.stubs.Reserverchambre.ReserverResponse.Builder.class);
    }

    public static final int RESERVATIONRESERVATION_FIELD_NUMBER = 1;
    private org.isd.stubs.Reserverchambre.ReservationResponse reservationReservation_;
    /**
     * <code>.ReservationResponse reservationReservation = 1;</code>
     * @return Whether the reservationReservation field is set.
     */
    public boolean hasReservationReservation() {
      return reservationReservation_ != null;
    }
    /**
     * <code>.ReservationResponse reservationReservation = 1;</code>
     * @return The reservationReservation.
     */
    public org.isd.stubs.Reserverchambre.ReservationResponse getReservationReservation() {
      return reservationReservation_ == null ? org.isd.stubs.Reserverchambre.ReservationResponse.getDefaultInstance() : reservationReservation_;
    }
    /**
     * <code>.ReservationResponse reservationReservation = 1;</code>
     */
    public org.isd.stubs.Reserverchambre.ReservationResponseOrBuilder getReservationReservationOrBuilder() {
      return getReservationReservation();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (reservationReservation_ != null) {
        output.writeMessage(1, getReservationReservation());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (reservationReservation_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getReservationReservation());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.isd.stubs.Reserverchambre.ReserverResponse)) {
        return super.equals(obj);
      }
      org.isd.stubs.Reserverchambre.ReserverResponse other = (org.isd.stubs.Reserverchambre.ReserverResponse) obj;

      if (hasReservationReservation() != other.hasReservationReservation()) return false;
      if (hasReservationReservation()) {
        if (!getReservationReservation()
            .equals(other.getReservationReservation())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasReservationReservation()) {
        hash = (37 * hash) + RESERVATIONRESERVATION_FIELD_NUMBER;
        hash = (53 * hash) + getReservationReservation().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.isd.stubs.Reserverchambre.ReserverResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.isd.stubs.Reserverchambre.ReserverResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.isd.stubs.Reserverchambre.ReserverResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.isd.stubs.Reserverchambre.ReserverResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.isd.stubs.Reserverchambre.ReserverResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.isd.stubs.Reserverchambre.ReserverResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.isd.stubs.Reserverchambre.ReserverResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.isd.stubs.Reserverchambre.ReserverResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.isd.stubs.Reserverchambre.ReserverResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.isd.stubs.Reserverchambre.ReserverResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.isd.stubs.Reserverchambre.ReserverResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.isd.stubs.Reserverchambre.ReserverResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.isd.stubs.Reserverchambre.ReserverResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ReserverResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ReserverResponse)
        org.isd.stubs.Reserverchambre.ReserverResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.isd.stubs.Reserverchambre.internal_static_ReserverResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.isd.stubs.Reserverchambre.internal_static_ReserverResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.isd.stubs.Reserverchambre.ReserverResponse.class, org.isd.stubs.Reserverchambre.ReserverResponse.Builder.class);
      }

      // Construct using org.isd.stubs.Reserverchambre.ReserverResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (reservationReservationBuilder_ == null) {
          reservationReservation_ = null;
        } else {
          reservationReservation_ = null;
          reservationReservationBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.isd.stubs.Reserverchambre.internal_static_ReserverResponse_descriptor;
      }

      @java.lang.Override
      public org.isd.stubs.Reserverchambre.ReserverResponse getDefaultInstanceForType() {
        return org.isd.stubs.Reserverchambre.ReserverResponse.getDefaultInstance();
      }

      @java.lang.Override
      public org.isd.stubs.Reserverchambre.ReserverResponse build() {
        org.isd.stubs.Reserverchambre.ReserverResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.isd.stubs.Reserverchambre.ReserverResponse buildPartial() {
        org.isd.stubs.Reserverchambre.ReserverResponse result = new org.isd.stubs.Reserverchambre.ReserverResponse(this);
        if (reservationReservationBuilder_ == null) {
          result.reservationReservation_ = reservationReservation_;
        } else {
          result.reservationReservation_ = reservationReservationBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.isd.stubs.Reserverchambre.ReserverResponse) {
          return mergeFrom((org.isd.stubs.Reserverchambre.ReserverResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.isd.stubs.Reserverchambre.ReserverResponse other) {
        if (other == org.isd.stubs.Reserverchambre.ReserverResponse.getDefaultInstance()) return this;
        if (other.hasReservationReservation()) {
          mergeReservationReservation(other.getReservationReservation());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.isd.stubs.Reserverchambre.ReserverResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.isd.stubs.Reserverchambre.ReserverResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private org.isd.stubs.Reserverchambre.ReservationResponse reservationReservation_;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.isd.stubs.Reserverchambre.ReservationResponse, org.isd.stubs.Reserverchambre.ReservationResponse.Builder, org.isd.stubs.Reserverchambre.ReservationResponseOrBuilder> reservationReservationBuilder_;
      /**
       * <code>.ReservationResponse reservationReservation = 1;</code>
       * @return Whether the reservationReservation field is set.
       */
      public boolean hasReservationReservation() {
        return reservationReservationBuilder_ != null || reservationReservation_ != null;
      }
      /**
       * <code>.ReservationResponse reservationReservation = 1;</code>
       * @return The reservationReservation.
       */
      public org.isd.stubs.Reserverchambre.ReservationResponse getReservationReservation() {
        if (reservationReservationBuilder_ == null) {
          return reservationReservation_ == null ? org.isd.stubs.Reserverchambre.ReservationResponse.getDefaultInstance() : reservationReservation_;
        } else {
          return reservationReservationBuilder_.getMessage();
        }
      }
      /**
       * <code>.ReservationResponse reservationReservation = 1;</code>
       */
      public Builder setReservationReservation(org.isd.stubs.Reserverchambre.ReservationResponse value) {
        if (reservationReservationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          reservationReservation_ = value;
          onChanged();
        } else {
          reservationReservationBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.ReservationResponse reservationReservation = 1;</code>
       */
      public Builder setReservationReservation(
          org.isd.stubs.Reserverchambre.ReservationResponse.Builder builderForValue) {
        if (reservationReservationBuilder_ == null) {
          reservationReservation_ = builderForValue.build();
          onChanged();
        } else {
          reservationReservationBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.ReservationResponse reservationReservation = 1;</code>
       */
      public Builder mergeReservationReservation(org.isd.stubs.Reserverchambre.ReservationResponse value) {
        if (reservationReservationBuilder_ == null) {
          if (reservationReservation_ != null) {
            reservationReservation_ =
              org.isd.stubs.Reserverchambre.ReservationResponse.newBuilder(reservationReservation_).mergeFrom(value).buildPartial();
          } else {
            reservationReservation_ = value;
          }
          onChanged();
        } else {
          reservationReservationBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.ReservationResponse reservationReservation = 1;</code>
       */
      public Builder clearReservationReservation() {
        if (reservationReservationBuilder_ == null) {
          reservationReservation_ = null;
          onChanged();
        } else {
          reservationReservation_ = null;
          reservationReservationBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.ReservationResponse reservationReservation = 1;</code>
       */
      public org.isd.stubs.Reserverchambre.ReservationResponse.Builder getReservationReservationBuilder() {
        
        onChanged();
        return getReservationReservationFieldBuilder().getBuilder();
      }
      /**
       * <code>.ReservationResponse reservationReservation = 1;</code>
       */
      public org.isd.stubs.Reserverchambre.ReservationResponseOrBuilder getReservationReservationOrBuilder() {
        if (reservationReservationBuilder_ != null) {
          return reservationReservationBuilder_.getMessageOrBuilder();
        } else {
          return reservationReservation_ == null ?
              org.isd.stubs.Reserverchambre.ReservationResponse.getDefaultInstance() : reservationReservation_;
        }
      }
      /**
       * <code>.ReservationResponse reservationReservation = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.isd.stubs.Reserverchambre.ReservationResponse, org.isd.stubs.Reserverchambre.ReservationResponse.Builder, org.isd.stubs.Reserverchambre.ReservationResponseOrBuilder> 
          getReservationReservationFieldBuilder() {
        if (reservationReservationBuilder_ == null) {
          reservationReservationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.isd.stubs.Reserverchambre.ReservationResponse, org.isd.stubs.Reserverchambre.ReservationResponse.Builder, org.isd.stubs.Reserverchambre.ReservationResponseOrBuilder>(
                  getReservationReservation(),
                  getParentForChildren(),
                  isClean());
          reservationReservation_ = null;
        }
        return reservationReservationBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ReserverResponse)
    }

    // @@protoc_insertion_point(class_scope:ReserverResponse)
    private static final org.isd.stubs.Reserverchambre.ReserverResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.isd.stubs.Reserverchambre.ReserverResponse();
    }

    public static org.isd.stubs.Reserverchambre.ReserverResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReserverResponse>
        PARSER = new com.google.protobuf.AbstractParser<ReserverResponse>() {
      @java.lang.Override
      public ReserverResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReserverResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ReserverResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ReserverResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.isd.stubs.Reserverchambre.ReserverResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReserverRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReserverRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReservationResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReservationResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReserverResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReserverResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025reserverchambre.proto\"N\n\017ReserverReque" +
      "st\022\017\n\007idOffre\030\001 \001(\005\022\016\n\006prenom\030\002 \001(\t\022\013\n\003n" +
      "om\030\003 \001(\t\022\r\n\005email\030\004 \001(\t\"U\n\023ReservationRe" +
      "sponse\022\017\n\007success\030\001 \001(\010\022\017\n\007message\030\002 \001(\t" +
      "\022\034\n\024reservationReference\030\003 \001(\t\"H\n\020Reserv" +
      "erResponse\0224\n\026reservationReservation\030\001 \001" +
      "(\0132\024.ReservationResponse2S\n\024HotelService" +
      "Reserver\022;\n\024effectuerReservation\022\020.Reser" +
      "verRequest\032\021.ReserverResponseB\017\n\rorg.isd" +
      ".stubsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ReserverRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ReserverRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReserverRequest_descriptor,
        new java.lang.String[] { "IdOffre", "Prenom", "Nom", "Email", });
    internal_static_ReservationResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ReservationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReservationResponse_descriptor,
        new java.lang.String[] { "Success", "Message", "ReservationReference", });
    internal_static_ReserverResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ReserverResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReserverResponse_descriptor,
        new java.lang.String[] { "ReservationReservation", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
